// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.
import { Document } from '@contentful/rich-text-types';
import { Asset, Entry } from 'contentful';

export interface IInspectionPageFields {
  /** Заголовок */
  title: string;

  /** Содержание */
  content: Document;
}

/** Страница */

export interface IInspectionPage extends Entry<IInspectionPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'inspectionPage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'inspectionPage';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
